### ISSUE TITLE
| blog

### ISSUE THREAD

**Issue by iainnnnn** [iainnnnn/Blog_comments#3]
https://qinyuyin.gitlab.io/blog/2018/06/18/hello-world/ 

 屏幕模式 ⌥⌘X 切换深色主题 ⌃⌘F 切换全屏模式 ⌥⌘L 切换黑暗模式  多个窗口，Split View 您可以同时打开多个窗口（⌥⌘N） 我们支持 MacOS 的 Split View，所以您可以在 Split View 中显示两个靠在一起的窗口。 您还可以在 Split View 中的另一个应用旁边或者在其自己的预览旁边显示 Ulysses 文稿。 您甚至可以打开所有的窗口，这使得您在编辑

**Comment by yinqy** [comment]
test
